version:   '3.9'

services:

  app:
    build: .
    env_file:
      - .env
      - .secrets
    volumes:
      - ./app:/home/code/app
      - ./tests:/home/code/tests
      - ./logger.ini:/home/code/logger.ini
    ports:
      - 8585:8080
    depends_on:
      - db
    command: bash -c "
      uvicorn app.main:app
      --log-config ./logger.ini
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors
      --reload --log-level debug
      "

  sqlserver:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    volumes:
      - sqlserver_data:/var/opt/mssql
    env_file:
      - .env
      - .secrets
    ports:
      - 1433:1433


  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
      - .secrets
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${SQL_USER}
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $SQL_DB -U $SQL_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  sqlserver_data:
