version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - gx.env
      - .secrets
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${SQL_USER}
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $SQL_DB -U $SQL_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: