version:   '3.9'

services:

  app:
    build: .
    env_file:
      - .env
      - .secrets
    volumes:
      - ./app:/home/code/app
      - ./tests:/home/code/tests
      - ./logger.ini:/home/code/logger.ini
      - ./sqlserver/setup:/home/code/setup
    ports:
      - 8585:8080
    depends_on:
      - sqlserver
    command: bash -c "
      uvicorn app.main:app
      --log-config ./logger.ini
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors
      --reload --log-level debug
      "

  sqlserver:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sqlserver/backup:/var/opt/mssql/backup
      - ./sqlserver/restore:/var/opt/mssql/restore
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/log

    env_file:
      - .env
      - .secrets
    environment:
      - SA_PASSWORD=Alaska2023
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433


volumes:
  sqlserver_data:
