[tool.poetry]
name = "fastapi-greatexpectations"
version = "0.0.1"
description = ""
authors = ["Jakub Miazek <the@grillazz.com>"]
readme = "README.md"
packages = [{include = "fastapi_greatexpectations"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = { extras = ["all"], version = "^0.95.1" }
great-expectations = "^0.16.11"
sqlacodegen = "^2.3.0.post1"
pytest = "^7.3.1"
psycopg = { extras = ["binary"], version = "^3.1.9" }
rich = "^13.3.4"
black = "^23.3.0"
isort = "^5.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
