name: CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
        poetry-version: [ "1.5.1" ]


    env:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      SA_PASSWORD: pass
      ACCEPT_EULA: Y

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: YourStrong!Passw0rd
          ACCEPT_EULA: Y
          MSSQL_PID: Developer
        ports:
          - 1433:1433
        run: |
          pwd
          ls -la
          cd /var/opt/mssql/backup/
          ls -la
          curl -L -o AdventureWorksLT2022.bak https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2022.bak
        options: --name=mssql --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'SELECT 1'" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - uses: actions/checkout@v3
      - name: Install SQL Server Tools
        run: sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
      - name: Download AdventureWorksLT2022 backup
        run: |
          pwd
          ls -la
          cd /var/opt/mssql/backup/
          ls -la
          curl -L -o AdventureWorksLT2022.bak https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2022.bak
      - name: Restore AdventureWorksLT2022 backup
#        working-directory: /opt/mssql-tools18/bin
#        run: sqlcmd -S mssql+pyodbc://sa@localhost:1433/master?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes -U SA -P ${{ env.SA_PASSWORD }} -Q "CREATE DATABASE AdventureWorksLT2022;"
        run: | 
          /opt/mssql-tools18/bin/sqlcmd -?
          /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -C -i /sqlserver/setup/restore-ci.sql
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Test Code Coverage
        run: poetry run coverage run -m pytest -v --cov=app --cov-report=xml
      - name: Coveralls
        uses: coverallsapp/github-action@v2
