name: CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
        poetry-version: [ "1.5.1" ]
#
#
#    env:
#      PYTHONDONTWRITEBYTECODE: 1
#      PYTHONUNBUFFERED: 1
#      SA_PASSWORD: pass
#      ACCEPT_EULA: Y

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: pass
          ACCEPT_EULA: Y
        ports:
          - 1433:1433

#      postgres:
#        image: postgres:14
#        env:
#          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
#          POSTGRES_PASSWORD: secret
#          POSTGRES_DB: testdb
#        ports:
#          - 5432:5432
#        # needed because the postgres container does not provide a health check
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install SQL Server Tools
        run: sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18



