
name: Unit Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
      fail-fast: false

    services:
      postgres:
        image: postgres:14
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: <--- Feed Database --->
        run: psql -d postgresql://postgres@localhost/testdb -f shakespeare.sql
        working-directory: ./db
        env:
          PGPASSWORD: secret
      - name: <--- Set up python --->
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: <--- Install project dependencies --->
        run: pip install -r requirements.txt
      - name: <--- Run tests --->
        run: pytest
        env:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          SQL_DB: testdb
          SQL_HOST: 127.0.0.1
          SQL_USER: postgres
          POSTGRES_PASSWORD: secret
          PGPASSWORD: secret

